### ISSUE TITLE
Unable to connect kafka outside containers programatically

### ISSUE THREAD

**Issue by prasantmathad** [cloudstax/firecamp#90]
Hi Support,

I am unable to connect kafka outside ecs containers through program. I tried connecting through Ip and as well DNS name. However I am able to telnet the kafka endpoint.

**### error connecting from Network Load Balancer:**

[Consumer clientId=consumer-1, groupId=group1] Discovered group coordinator mykafka-2.LAWSHBKAFD01AP01-firecamp.com:9092 (id: 2147483645 rack: null)
2019-02-19 17:19:23.054  INFO [hbi-logging-service,,,] 8812 --- [ntainer#0-0-C-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=group1] Group coordinator mykafka-2.LAWSHBKAFD01AP01-firecamp.com:9092 (id: 2147483645 rack: null) is unavailable or invalid, will attempt rediscovery 

**### **error connecting from IP:****
java.io.IOException: Can't resolve address: mykafka-0.LAWSHBKAFD01AP01-firecamp.com:9092
              at org.apache.kafka.common.network.Selector.doConnect(Selector.java:235) ~[kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.common.network.Selector.connect(Selector.java:214) ~[kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:864) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.NetworkClient.access$700(NetworkClient.java:64) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1035) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:920) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:508) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:271) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:243) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:314) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1218) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1175) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1154) [kafka-clients-2.0.1.jar:na]
              at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:732) [spring-kafka-2.2.3.RELEASE.jar:2.2.3.RELEASE]
              at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:689) [spring-kafka-2.2.3.RELEASE.jar:2.2.3.RELEASE]
              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_51]
              at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_51]
              at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
Caused by: java.nio.channels.UnresolvedAddressException: null
              at sun.nio.ch.Net.checkAddress(Net.java:123) ~[na:1.8.0_51]
              at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622) ~[na:1.8.0_51]
              at org.apache.kafka.common.network.Selector.doConnect(Selector.java:233) ~[kafka-clients-2.0.1.jar:na]
              ... 20 common frames omitted

2019-02-19 18:43:28.023  WARN 2976 --- [ntainer#0-0-C-1] org.apache.kafka.clients.NetworkClient   : [Consumer clientId=consumer-2, groupId=product] Error connecting to node mykafka-1.LAWSHBKAFD01AP01-firecamp.com:9092 (id: 1 rack: eu-west-1b)

java.io.IOException: Can't resolve address: mykafka-1.LAWSHBKAFD01AP01-firecamp.com:9092
              at org.apache.kafka.common.network.Selector.doConnect(Selector.java:235) ~[kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.common.network.Selector.connect(Selector.java:214) ~[kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:864) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.NetworkClient.access$700(NetworkClient.java:64) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1035) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:920) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:508) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:271) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:243) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:314) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1218) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1175) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1154) [kafka-clients-2.0.1.jar:na]
              at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:732) [spring-kafka-2.2.3.RELEASE.jar:2.2.3.RELEASE]
              at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:689) [spring-kafka-2.2.3.RELEASE.jar:2.2.3.RELEASE]
              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_51]
              at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_51]
              at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
Caused by: java.nio.channels.UnresolvedAddressException: null
              at sun.nio.ch.Net.checkAddress(Net.java:123) ~[na:1.8.0_51]
              at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622) ~[na:1.8.0_51]
              at org.apache.kafka.common.network.Selector.doConnect(Selector.java:233) ~[kafka-clients-2.0.1.jar:na]
              ... 20 common frames omitted

2019-02-19 18:43:28.398  WARN 2976 --- [ntainer#0-0-C-1] org.apache.kafka.clients.NetworkClient   : [Consumer clientId=consumer-2, groupId=product] Error connecting to node mykafka-2.LAWSHBKAFD01AP01-firecamp.com:9092 (id: 2 rack: eu-west-1c)

java.io.IOException: Can't resolve address: mykafka-2.LAWSHBKAFD01AP01-firecamp.com:9092
              at org.apache.kafka.common.network.Selector.doConnect(Selector.java:235) ~[kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.common.network.Selector.connect(Selector.java:214) ~[kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:864) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.NetworkClient.access$700(NetworkClient.java:64) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1035) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:920) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:508) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:271) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:243) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:314) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1218) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1175) [kafka-clients-2.0.1.jar:na]
              at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1154) [kafka-clients-2.0.1.jar:na]
              at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:732) [spring-kafka-2.2.3.RELEASE.jar:2.2.3.RELEASE]
              at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:689) [spring-kafka-2.2.3.RELEASE.jar:2.2.3.RELEASE]
              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_51]
              at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_51]
              at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
Caused by: java.nio.channels.UnresolvedAddressException: null
              at sun.nio.ch.Net.checkAddress(Net.java:123) ~[na:1.8.0_51]
              at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622) ~[na:1.8.0_51]
              at org.apache.kafka.common.network.Selector.doConnect(Selector.java:233) ~[kafka-clients-2.0.1.jar:na]
              ... 20 common frames omitted

**Comment by JuniusLuo** [comment]
CloudFormation stack returns the VPCID and AppAccessSecurityGroup. Please check whether your program running in the same VPC and AppAccessSecurityGroup.

**Comment by prasantmathad** [comment]
Our program in different vpc
